#!/usr/bin/env python3
"""
compress_context.py — Compress old context files into token-efficient summaries.

What it does:
1. Reads files older than STALE_DAYS in board_reports/ and goals/
2. Generates ~50-100 token summaries
3. Moves originals to archive/raw/<category>/<file>
4. Writes summary entries to archive/<category>/<date>.summary.md
5. Updates archive/ARCHIVE_INDEX.md

Usage:
    python3 scripts/compress_context.py [--stale-days 30] [--dry-run]

Configuration:
    STALE_DAYS: age in days after which a file is "stale" (default: 14)
    DRY_RUN: preview without moving/generating (default: False)

No external dependencies. Standard library only.
"""

import os
import sys
import json
import shutil
import hashlib
import datetime
import argparse
from pathlib import Path
from collections import defaultdict

REPO_ROOT = Path(__file__).parent.parent.resolve()
STALE_DAYS = 14

CATEGORIES = {
    "board_reports": "board reports",
    "goals": "goals",
}

TEMPLATE_SUMMARY = """\
## {date} — {title}

**Priority:** {priority}
**Topics:** {topics}
**Key decisions:** {decisions}
**Status:** {status}
**Original:** `archive/raw/{category}/{filename}`
**Tokens saved:** ~{tokens_saved}

{notes}
"""


def token_estimate(text: str) -> int:
    """Rough token estimate (~2.5 tokens/line avg for markdown)."""
    lines = text.split("\n")
    return max(1, int(len(lines) * 2.5) + len(text) // 4)


def extract_metadata(content: str, filename: str) -> dict:
    """Extract minimal metadata from a markdown file for compression."""
    lines = content.split("\n")
    title = filename.replace(".md", "").replace("_", " ").replace("-", " ").title()
    first_line = ""
    for line in lines[:5]:
        s = line.strip()
        if s.startswith("# "):
            title = s.lstrip("# ").strip()
        elif s and not first_line:
            first_line = s[:120]

    topics = first_line[:80] if first_line else "general"
    return {
        "title": title,
        "topics": topics,
        "first_line": first_line,
        "lines": len(lines),
        "tokens": token_estimate(content),
        "hash": hashlib.md5(content.encode()).hexdigest()[:12],
    }


def generate_summary(meta: dict, category: str, filename: str, date_str: str) -> str:
    """Generate a ~50-100 token summary entry."""
    tokens_saved = meta["tokens"]
    notes = meta["first_line"][:200] if meta["first_line"] else "Archived."
    return TEMPLATE_SUMMARY.format(
        date=date_str,
        title=meta["title"],
        priority="low" if meta["tokens"] < 100 else "medium",
        topics=meta["topics"],
        decisions="See original",
        status="archived",
        category=category,
        filename=filename,
        tokens_saved=tokens_saved,
        notes=notes,
    )


def update_archive_index(archive_root: Path) -> None:
    """Regenerate ARCHIVE_INDEX.md from all .summary.md files in archive/."""
    index_path = archive_root / "ARCHIVE_INDEX.md"
    summaries = sorted(archive_root.rglob("*.summary.md"))

    lines = [
        "# ARCHIVE_INDEX.md — Compressed Context Archive",
        "",
        "**Auto-generated by scripts/compress_context.py**",
        f"**Last updated:** {datetime.date.today().isoformat()}",
        "",
        "Files here are compressed summaries of context older than 14 days.",
        "Each summary is ~50-100 tokens — cheap to load on demand.",
        "Originals preserved in `archive/raw/` if you need full fidelity.",
        "",
        "## Contents",
        "",
    ]

    for s in summaries:
        rel = s.relative_to(archive_root).as_posix()
        lines.append(f"- [{s.stem}]({rel})")

    lines.extend([
        "",
        "---",
        "",
        "## Full index",
        "",
    ])

    for s in summaries:
        content = s.read_text()
        lines.append(content)
        lines.append("---\n")

    index_path.write_text("\n".join(lines) + "\n")
    print(f"  ✓ Updated {index_path.name}")


def compress_directory(category: str, cat_path: Path, archive_root: Path, stale_days: int, dry_run: bool):
    """Compress old files in a category directory."""
    if not cat_path.exists():
        print(f"  - {category}/ not found, skipping")
        return

    now = datetime.datetime.now()
    target_dir = archive_root / category
    raw_dir = archive_root / "raw" / category
    raw_dir.mkdir(parents=True, exist_ok=True)
    target_dir.mkdir(parents=True, exist_ok=True)

    compressed = []

    for f in sorted(cat_path.glob("*.md")):
        if f.name in ("README.md",):
            continue

        mtime = datetime.datetime.fromtimestamp(f.stat().st_mtime)
        age_days = (now - mtime).days

        if age_days < stale_days:
            continue

        content = f.read_text()
        meta = extract_metadata(content, f.name)

        date_str = f.name[:10] if f.name[:1].isdigit() else mtime.strftime("%Y-%m-%d")
        summary = generate_summary(meta, category, f.name, date_str)

        summary_file = target_dir / f"{date_str}_{f.name}"

        if not dry_run:
            # Write summary
            summary_file.write_text(summary)
            # Move original to raw archive
            shutil.move(str(f), str(raw_dir / f.name))
            print(f"  ✓ {category}/{f.name} → archive ({meta['tokens']} tok → ~75 tok, saved ~{meta['tokens']-75})")
        else:
            print(f"  [DRY-RUN] {category}/{f.name}: {meta['tokens']} tok → ~75 tok (saves ~{meta['tokens']-75})")

        compressed.append((category, f.name, meta))

    if compressed and not dry_run:
        update_archive_index(archive_root)
        total_saved = sum(m["tokens"] - 75 for _, _, m in compressed)
        print(f"\n  Total tokens saved: ~{total_saved} across {len(compressed)} files")

    return compressed


def main():
    parser = argparse.ArgumentParser(description="Compress old context files into summaries")
    parser.add_argument("--stale-days", type=int, default=STALE_DAYS, help="Days after which to compress")
    parser.add_argument("--dry-run", action="store_true", help="Preview only, no changes")
    args = parser.parse_args()

    archive_root = REPO_ROOT / "archive"
    archive_root.mkdir(exist_ok=True)

    print(f"🔍 Scanning for stale files (>={args.stale_days} days old)...\n")

    total = []
    for dirname, _ in CATEGORIES.items():
        result = compress_directory(dirname, REPO_ROOT / dirname, archive_root, args.stale_days, args.dry_run)
        if result:
            total.extend(result)

    if not total:
        print("  No stale files found — everything is current.")

    print(f"\n{'DRY-RUN: ' if args.dry_run else ''}Done. {len(total)} files processed.")


if __name__ == "__main__":
    main()
