#!/usr/bin/env bash
# context_maintenance.sh
# Generates 00_hot/HOT_CONTEXT.md from:
#   - SYSTEM-STATE-TODAY → current_state
#   - buying-agent/goals/ → current_goal
#   - buying-agent/board_reports/ → board_latest_ref
#   - git diff --stat of last commit → last_git_diff
#
# Usage:
#   bash scripts/context_maintenance.sh          # write HOT_CONTEXT.md
#   bash scripts/context_maintenance.sh --dry-run # print diff without writing

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
HOT_DIR="$REPO_DIR/00_hot"
OUTPUT="$HOT_DIR/HOT_CONTEXT.md"
DRY_RUN="${1:-}"

# ── Collect sources ──────────────────────────────────────────────────

# current_state: from system-context-for-claude
STATE_FILE="$HOME/system-context-for-claude/15-SYSTEM-STATE-TODAY.md"
if [ -f "$STATE_FILE" ]; then
  CURRENT_STATE=$(head -40 "$STATE_FILE" | grep -v '^$' | head -25)
else
  CURRENT_STATE="(no system state file found)"
fi

# current_goal: latest goal file in buying-agent/goals/
GOAL_FILE=$(ls -t "$REPO_DIR/goals/"*.md 2>/dev/null | head -1)
if [ -n "$GOAL_FILE" ]; then
  CURRENT_GOAL=$(head -30 "$GOAL_FILE" | grep -v '^$' | head -15)
else
  CURRENT_GOAL="(no goal file found)"
fi

# board_latest_ref: latest board report
BOARD_FILE=$(ls -t "$REPO_DIR/board_reports/"*.md 2>/dev/null | head -1)
if [ -n "$BOARD_FILE" ]; then
  BOARD_LATEST_REF=$(basename "$BOARD_FILE")
  BOARD_SUMMARY=$(head -10 "$BOARD_FILE" | grep -v '^$' | head -8)
else
  BOARD_LATEST_REF="(no board report found)"
  BOARD_SUMMARY=""
fi

# last_git_diff: git diff --stat of the last commit
cd "$REPO_DIR"
LAST_GIT_DIFF=$(git --no-pager diff --stat HEAD~1 HEAD 2>/dev/null || echo "(no previous commit to diff against)")
GIT_LOG_LATEST=$(git --no-pager log --oneline -3 2>/dev/null || echo "(no git history)")

# ── Build output ─────────────────────────────────────────────────────

GENERATED_AT="$(date '+%Y-%m-%dT%H:%M:%S%z')"

build_context() {
cat <<EOF
# HOT_CONTEXT.md — Generated ${GENERATED_AT}

> Auto-generated by scripts/context_maintenance.sh. Do not hand-edit.

---

## current_state

\`\`\`
${CURRENT_STATE}
\`\`\`

---

## current_goal

File: \`$(basename "${GOAL_FILE:-unknown}")\`

\`\`\`
${CURRENT_GOAL}
\`\`\`

---

## board_latest_ref

File: \`${BOARD_LATEST_REF}\`

\`\`\`
${BOARD_SUMMARY}
\`\`\`

---

## last_git_diff

Recent commits:
\`\`\`
${GIT_LOG_LATEST}
\`\`\`

Diff from last commit:
\`\`\`
${LAST_GIT_DIFF}
\`\`\`
EOF
}

# ── Dry-run or write ─────────────────────────────────────────────────

if [ "$DRY_RUN" = "--dry-run" ]; then
  mkdir -p "$HOT_DIR"
  TEMP_OUTPUT=$(mktemp)
  build_context > "$TEMP_OUTPUT"
  echo "[DRY-RUN] Would write to: $OUTPUT"
  echo "[DRY-RUN] Diff vs current file:"
  if [ -f "$OUTPUT" ]; then
    diff --color=always "$OUTPUT" "$TEMP_OUTPUT" 2>/dev/null || true
  else
    echo "  (no current file — would create new)"
    echo ""
    head -5 "$TEMP_OUTPUT"
    echo "  ..."
  fi
  rm "$TEMP_OUTPUT"
  exit 0
fi

mkdir -p "$HOT_DIR"
build_context > "$OUTPUT"
echo "[OK] Generated: $OUTPUT"
echo "  Sections: current_state, current_goal, board_latest_ref, last_git_diff"
